/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uns_media_ffmpegnative_FFmpegTool */

#ifndef _Included_com_uns_media_ffmpegnative_FFmpegTool
#define _Included_com_uns_media_ffmpegnative_FFmpegTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uns_media_ffmpegnative_FFmpegTool
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_uns_media_ffmpegnative_FFmpegTool_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
